### ISSUE TITLE
Infinite Points Glitch

### ISSUE THREAD

**Issue by FEB23** [yazawa69/Flappy_Bird_Clone#1]
Point s  arent calculating properly. Sometimes the just go up and up and up.
Really destroys the fun of the game. 
Please Fix. 
User score 2/10
Critic Score 10/10

**Comment by yazawa69** [comment]
Dear Mr. FEB23,

Thank you for letting us know about this bug, this helps immensely to improve our code.
The Flappy_Bird_Clone team has immediately considered this problem,
and we came to the conclusion, that this is in fact a feature and not a bug.

just kidding its fixed ; )

Sincerely,
Your Flappy_Bird_Team
